// Vocabulary Data - N5, N4, N3, N2, N1
// Organized by JLPT level with furigana, romaji, meaning, and type

export const VOCAB_DATA = {
  n5: {
    title: "JLPT N5 Vocabulary",
    description: "Essential vocabulary for beginners. Approximately 800 words covering daily life topics.",
    vocabulary: [
      // Numbers & Time
      { word: "一", furigana: "いち", romaji: "ichi", meaning: "one", type: "Number" },
      { word: "二", furigana: "に", romaji: "ni", meaning: "two", type: "Number" },
      { word: "三", furigana: "さん", romaji: "san", meaning: "three", type: "Number" },
      { word: "四", furigana: "よん, し", romaji: "yon, shi", meaning: "four", type: "Number" },
      { word: "五", furigana: "ご", romaji: "go", meaning: "five", type: "Number" },
      { word: "六", furigana: "ろく", romaji: "roku", meaning: "six", type: "Number" },
      { word: "七", furigana: "なな, しち", romaji: "nana, shichi", meaning: "seven", type: "Number" },
      { word: "八", furigana: "はち", romaji: "hachi", meaning: "eight", type: "Number" },
      { word: "九", furigana: "きゅう, く", romaji: "kyuu, ku", meaning: "nine", type: "Number" },
      { word: "十", furigana: "じゅう", romaji: "juu", meaning: "ten", type: "Number" },
      { word: "百", furigana: "ひゃく", romaji: "hyaku", meaning: "hundred", type: "Number" },
      { word: "千", furigana: "せん", romaji: "sen", meaning: "thousand", type: "Number" },
      { word: "万", furigana: "まん", romaji: "man", meaning: "ten thousand", type: "Number" },
      { word: "円", furigana: "えん", romaji: "en", meaning: "yen", type: "Money" },
      { word: "今日", furigana: "きょう", romaji: "kyou", meaning: "today", type: "Time" },
      { word: "明日", furigana: "あした", romaji: "ashita", meaning: "tomorrow", type: "Time" },
      { word: "昨日", furigana: "きのう", romaji: "kinou", meaning: "yesterday", type: "Time" },
      { word: "今", furigana: "いま", romaji: "ima", meaning: "now", type: "Time" },
      { word: "朝", furigana: "あさ", romaji: "asa", meaning: "morning", type: "Time" },
      { word: "昼", furigana: "ひる", romaji: "hiru", meaning: "noon, daytime", type: "Time" },
      { word: "夜", furigana: "よる", romaji: "yoru", meaning: "night", type: "Time" },
      { word: "時", furigana: "じ", romaji: "ji", meaning: "o'clock", type: "Time" },
      { word: "分", furigana: "ふん, ぷん", romaji: "fun, pun", meaning: "minute", type: "Time" },
      { word: "時間", furigana: "じかん", romaji: "jikan", meaning: "time", type: "Time" },
      { word: "週間", furigana: "しゅうかん", romaji: "shuukan", meaning: "week", type: "Time" },
      { word: "年", furigana: "ねん", romaji: "nen", meaning: "year", type: "Time" },
      { word: "月", furigana: "つき", romaji: "tsuki", meaning: "month, moon", type: "Time" },
      { word: "日", furigana: "ひ, か", romaji: "hi, ka", meaning: "day, sun", type: "Time" },

      // People & Relationships
      { word: "人", furigana: "ひと", romaji: "hito", meaning: "person", type: "Noun" },
      { word: "日本人", furigana: "にほんじん", romaji: "nihonjin", meaning: "Japanese person", type: "Noun" },
      { word: "学生", furigana: "がくせい", romaji: "gakusei", meaning: "student", type: "Noun" },
      { word: "先生", furigana: "せんせい", romaji: "sensei", meaning: "teacher", type: "Noun" },
      { word: "友達", furigana: "ともだち", romaji: "tomodachi", meaning: "friend", type: "Noun" },
      { word: "家族", furigana: "かぞく", romaji: "kazoku", meaning: "family", type: "Noun" },
      { word: "父", furigana: "ちち", romaji: "chichi", meaning: "father", type: "Noun" },
      { word: "母", furigana: "はは", romaji: "haha", meaning: "mother", type: "Noun" },
      { word: "男", furigana: "おとこ", romaji: "otoko", meaning: "man", type: "Noun" },
      { word: "女", furigana: "おんな", romaji: "onna", meaning: "woman", type: "Noun" },
      { word: "子供", furigana: "こども", romaji: "kodomo", meaning: "child", type: "Noun" },
      { word: "彼", furigana: "かれ", romaji: "kare", meaning: "he, boyfriend", type: "Pronoun" },
      { word: "彼女", furigana: "かのじょ", romaji: "kanojo", meaning: "she, girlfriend", type: "Pronoun" },
      { word: "私", furigana: "わたし", romaji: "watashi", meaning: "I, me", type: "Pronoun" },

      // Places & Buildings
      { word: "家", furigana: "いえ, うち", romaji: "ie, uchi", meaning: "house, home", type: "Place" },
      { word: "学校", furigana: "がっこう", romaji: "gakkou", meaning: "school", type: "Place" },
      { word: "駅", furigana: "えき", romaji: "eki", meaning: "station", type: "Place" },
      { word: "店", furigana: "みせ", romaji: "mise", meaning: "shop", type: "Place" },
      { word: "会社", furigana: "かいしゃ", romaji: "kaisha", meaning: "company", type: "Place" },
      { word: "病院", furigana: "びょういん", romaji: "byouin", meaning: "hospital", type: "Place" },
      { word: "図書館", furigana: "としょかん", romaji: "toshokan", meaning: "library", type: "Place" },
      { word: "公園", furigana: "こうえん", romaji: "kouen", meaning: "park", type: "Place" },
      { word: "日本", furigana: "にほん", romaji: "nihon", meaning: "Japan", type: "Place" },
      { word: "東京", furigana: "とうきょう", romaji: "toukyou", meaning: "Tokyo", type: "Place" },

      // Nature & Weather
      { word: "山", furigana: "やま", romaji: "yama", meaning: "mountain", type: "Nature" },
      { word: "川", furigana: "かわ", romaji: "kawa", meaning: "river", type: "Nature" },
      { word: "海", furigana: "うみ", romaji: "umi", meaning: "sea", type: "Nature" },
      { word: "空", furigana: "そら", romaji: "sora", meaning: "sky", type: "Nature" },
      { word: "雨", furigana: "あめ", romaji: "ame", meaning: "rain", type: "Weather" },
      { word: "雪", furigana: "ゆき", romaji: "yuki", meaning: "snow", type: "Weather" },
      { word: "風", furigana: "かぜ", romaji: "kaze", meaning: "wind", type: "Weather" },
      { word: "天気", furigana: "てんき", romaji: "tenki", meaning: "weather", type: "Weather" },
      { word: "火", furigana: "ひ", romaji: "hi", meaning: "fire", type: "Nature" },
      { word: "水", furigana: "みず", romaji: "mizu", meaning: "water", type: "Nature" },

      // Food & Drink
      { word: "水", furigana: "みず", romaji: "mizu", meaning: "water", type: "Drink" },
      { word: "お茶", furigana: "おちゃ", romaji: "ocha", meaning: "tea", type: "Drink" },
      { word: "コーヒー", furigana: "こーひー", romaji: "koohii", meaning: "coffee", type: "Drink" },
      { word: "牛乳", furigana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "milk", type: "Drink" },
      { word: "ご飯", furigana: "ごはん", romaji: "gohan", meaning: "rice, meal", type: "Food" },
      { word: "パン", furigana: "ぱん", romaji: "pan", meaning: "bread", type: "Food" },
      { word: "卵", furigana: "たまご", romaji: "tamago", meaning: "egg", type: "Food" },
      { word: "肉", furigana: "にく", romaji: "niku", meaning: "meat", type: "Food" },
      { word: "魚", furigana: "さかな", romaji: "sakana", meaning: "fish", type: "Food" },
      { word: "野菜", furigana: "やさい", romaji: "yasai", meaning: "vegetable", type: "Food" },
      { word: "果物", furigana: "くだもの", romaji: "kudamono", meaning: "fruit", type: "Food" },
      { word: "食べる", furigana: "たべる", romaji: "taberu", meaning: "to eat", type: "Verb" },
      { word: "飲む", furigana: "のむ", romaji: "nomu", meaning: "to drink", type: "Verb" },
      { word: "朝ご飯", furigana: "あさごはん", romaji: "asagohan", meaning: "breakfast", type: "Food" },
      { word: "昼ご飯", furigana: "ひるごはん", romaji: "hirugohan", meaning: "lunch", type: "Food" },
      { word: "晩ご飯", furigana: "ばんごはん", romaji: "bangohan", meaning: "dinner", type: "Food" },

      // Daily Items
      { word: "本", furigana: "ほん", romaji: "hon", meaning: "book", type: "Noun" },
      { word: "新聞", furigana: "しんぶん", romaji: "shinbun", meaning: "newspaper", type: "Noun" },
      { word: "雑誌", furigana: "ざっし", romaji: "zasshi", meaning: "magazine", type: "Noun" },
      { word: "手紙", furigana: "てがみ", romaji: "tegami", meaning: "letter", type: "Noun" },
      { word: "電話", furigana: "でんわ", romaji: "denwa", meaning: "telephone", type: "Noun" },
      { word: "時計", furigana: "とけい", romaji: "tokei", meaning: "clock, watch", type: "Noun" },
      { word: "傘", furigana: "かさ", romaji: "kasa", meaning: "umbrella", type: "Noun" },
      { word: "鍵", furigana: "かぎ", romaji: "kagi", meaning: "key", type: "Noun" },
      { word: "車", furigana: "くるま", romaji: "kuruma", meaning: "car", type: "Noun" },
      { word: "電車", furigana: "でんしゃ", romaji: "densha", meaning: "train", type: "Noun" },
      { word: "バス", furigana: "ばす", romaji: "basu", meaning: "bus", type: "Noun" },
      { word: "切符", furigana: "きっぷ", romaji: "kippu", meaning: "ticket", type: "Noun" },

      // Body Parts
      { word: "目", furigana: "め", romaji: "me", meaning: "eye", type: "Body" },
      { word: "耳", furigana: "みみ", romaji: "mimi", meaning: "ear", type: "Body" },
      { word: "口", furigana: "くち", romaji: "kuchi", meaning: "mouth", type: "Body" },
      { word: "手", furigana: "て", romaji: "te", meaning: "hand", type: "Body" },
      { word: "足", furigana: "あし", romaji: "ashi", meaning: "foot, leg", type: "Body" },
      { word: "頭", furigana: "あたま", romaji: "atama", meaning: "head", type: "Body" },
      { word: "体", furigana: "からだ", romaji: "karada", meaning: "body", type: "Body" },

      // Adjectives - い
      { word: "大きい", furigana: "おおきい", romaji: "ookii", meaning: "big", type: "Adjective" },
      { word: "小さい", furigana: "ちいさい", romaji: "chiisai", meaning: "small", type: "Adjective" },
      { word: "新しい", furigana: "あたらしい", romaji: "atarashii", meaning: "new", type: "Adjective" },
      { word: "古い", furigana: "ふるい", romaji: "furui", meaning: "old (thing)", type: "Adjective" },
      { word: "良い", furigana: "よい, いい", romaji: "yoi, ii", meaning: "good", type: "Adjective" },
      { word: "悪い", furigana: "わるい", romaji: "warui", meaning: "bad", type: "Adjective" },
      { word: "高い", furigana: "たかい", romaji: "takai", meaning: "expensive, tall", type: "Adjective" },
      { word: "安い", furigana: "やすい", romaji: "yasui", meaning: "cheap", type: "Adjective" },
      { word: "低い", furigana: "ひくい", romaji: "hikui", meaning: "low, short", type: "Adjective" },
      { word: "長い", furigana: "ながい", romaji: "nagai", meaning: "long", type: "Adjective" },
      { word: "短い", furigana: "みじかい", romaji: "mijikai", meaning: "short (length)", type: "Adjective" },
      { word: "赤い", furigana: "あかい", romaji: "akai", meaning: "red", type: "Adjective" },
      { word: "青い", furigana: "あおい", romaji: "aoi", meaning: "blue", type: "Adjective" },
      { word: "白い", furigana: "しろい", romaji: "shiroi", meaning: "white", type: "Adjective" },
      { word: "黒い", furigana: "くろい", romaji: "kuroi", meaning: "black", type: "Adjective" },
      { word: "おいしい", furigana: "おいしい", romaji: "oishii", meaning: "delicious", type: "Adjective" },
      { word: "まずい", furigana: "まずい", romaji: "mazui", meaning: "un Delicious", type: "Adjective" },
      { word: "寒い", furigana: "さむい", romaji: "samui", meaning: "cold (weather)", type: "Adjective" },
      { word: "暑い", furigana: "あつい", romaji: "atsui", meaning: "hot (weather)", type: "Adjective" },
      { word: "冷たい", furigana: "つめたい", romaji: "tsumetai", meaning: "cold (thing)", type: "Adjective" },
      { word: "温かい", furigana: "あたたかい", romaji: "atatakai", meaning: "warm", type: "Adjective" },
      { word: "易しい", furigana: "やさしい", romaji: "yasashii", meaning: "easy", type: "Adjective" },
      { word: "難しい", furigana: "むずかしい", romaji: "muzukashii", meaning: "difficult", type: "Adjective" },
      { word: "忙しい", furigana: "いそがしい", romaji: "isogashii", meaning: "busy", type: "Adjective" },
      { word: "有余", furigana: "ゆうめい", romaji: "yuumei", meaning: "famous", type: "Adjective" },

      // Adjectives - な
      { word: "静か", furigana: "しずか", romaji: "shizuka", meaning: "quiet", type: "Adjective" },
      { word: "綺麗", furigana: "きれい", romaji: "kirei", meaning: "beautiful, clean", type: "Adjective" },
      { word: "暇", furigana: "ひま", romaji: "hima", meaning: "free, not busy", type: "Adjective" },
      { word: "便利", furigana: "べんり", romaji: "benri", meaning: "convenient", type: "Adjective" },
      { word: "不便", furigana: "ふべん", romaji: "fuben", meaning: "inconvenient", type: "Adjective" },
      { word: "好き", furigana: "すき", romaji: "suki", meaning: "like", type: "Adjective" },
      { word: "嫌い", furigana: "きらい", romaji: "kirai", meaning: "dislike", type: "Adjective" },
      { word: "上手", furigana: "じょうず", romaji: "jouzu", meaning: "good at", type: "Adjective" },
      { word: "下手", furigana: "へた", romaji: "heta", meaning: "bad at", type: "Adjective" },

      // Verbs
      { word: "見る", furigana: "みる", romaji: "miru", meaning: "to see, watch", type: "Verb" },
      { word: "聞く", furigana: "きく", romaji: "kiku", meaning: "to hear, ask", type: "Verb" },
      { word: "読む", furigana: "よむ", romaji: "yomu", meaning: "to read", type: "Verb" },
      { word: "書く", furigana: "かく", romaji: "kaku", meaning: "to write", type: "Verb" },
      { word: "話す", furigana: "はなす", romaji: "hanasu", meaning: "to speak", type: "Verb" },
      { word: "聞く", furigana: "きく", romaji: "kiku", meaning: "to listen", type: "Verb" },
      { word: "行く", furigana: "いく", romaji: "iku", meaning: "to go", type: "Verb" },
      { word: "来る", furigana: "くる", romaji: "kuru", meaning: "to come", type: "Verb" },
      { word: "帰る", furigana: "かえる", romaji: "kaeru", meaning: "to return home", type: "Verb" },
      { word: "買う", furigana: "かう", romaji: "kau", meaning: "to buy", type: "Verb" },
      { word: "売る", furigana: "うる", romaji: "uru", meaning: "to sell", type: "Verb" },
      { word: "食べる", furigana: "たべる", romaji: "taberu", meaning: "to eat", type: "Verb" },
      { word: "飲む", furigana: "のむ", romaji: "nomu", meaning: "to drink", type: "Verb" },
      { word: "寝る", furigana: "ねる", romaji: "neru", meaning: "to sleep", type: "Verb" },
      { word: "起きる", furigana: "おきる", romaji: "okiru", meaning: "to wake up", type: "Verb" },
      { word: "待つ", furigana: "まつ", romaji: "matsu", meaning: "to wait", type: "Verb" },
      { word: "作る", furigana: "つくる", romaji: "tsukuru", meaning: "to make", type: "Verb" },
      { word: "入る", furigana: "はいる", romaji: "hairu", meaning: "to enter", type: "Verb" },
      { word: "出る", furigana: "でる", romaji: "deru", meaning: "to leave, exit", type: "Verb" },
      { word: "使う", furigana: "つかう", romaji: "tsukau", meaning: "to use", type: "Verb" },
      { word: "知る", furigana: "しる", romaji: "shiru", meaning: "to know", type: "Verb" },
      { word: "思う", furigana: "おもう", romaji: "omou", meaning: "to think", type: "Verb" },
      { word: "分かる", furigana: "わかる", romaji: "wakaru", meaning: "to understand", type: "Verb" },
      { word: "教える", furigana: "おしえる", romaji: "oshieru", meaning: "to teach", type: "Verb" },
      { word: "習う", furigana: "ならう", romaji: "narau", meaning: "to learn", type: "Verb" },
      { word: "ある", furigana: "ある", romaji: "aru", meaning: "to exist (thing)", type: "Verb" },
      { word: "いる", furigana: "いる", romaji: "iru", meaning: "to exist (living)", type: "Verb" },
      { word: "生まれる", furigana: "うまれる", romaji: "umareru", meaning: "to be born", type: "Verb" },
      { word: "死ぬ", furigana: "しぬ", romaji: "shinu", meaning: "to die", type: "Verb" },
    ]
  },

  n4: {
    title: "JLPT N4 Vocabulary",
    description: "Elementary vocabulary. Approximately 1,500 words for daily situations.",
    vocabulary: [
      // Business & Work
      { word: "仕事", furigana: "しごと", romaji: "shigoto", meaning: "work, job", type: "Noun" },
      { word: "会社", furigana: "かいしゃ", romaji: "kaisha", meaning: "company", type: "Noun" },
      { word: "社長", furigana: "しゃちょう", romaji: "shachou", meaning: "company president", type: "Noun" },
      { word: "社員", furigana: "しゃいん", romaji: "shain", meaning: "employee", type: "Noun" },
      { word: "会議", furigana: "かいぎ", romaji: "kaigi", meaning: "meeting", type: "Noun" },
      { word: "書類", furigana: "しょるい", romaji: "shorui", meaning: "documents", type: "Noun" },
      { word: " Fax", furigana: " fax", romaji: "fax", meaning: "fax", type: "Noun" },
      { word: "コピー", furigana: "こぴー", romaji: "kopii", meaning: "copy", type: "Noun" },
      { word: "通勤", furigana: "つうきん", romaji: "tsuukin", meaning: "commuting", type: "Noun" },
      { word: "出張", furigana: "しゅっちょう", romaji: "shucchou", meaning: "business trip", type: "Noun" },
      { word: "休む", furigana: "やすむ", romaji: "yasumu", meaning: "to be absent, rest", type: "Verb" },
      { word: "終わる", furigana: "おわる", romaji: "owaru", meaning: "to end", type: "Verb" },
      { word: "始める", furigana: "はじめる", romaji: "hajimeru", meaning: "to begin", type: "Verb" },
      { word: "練習", furigana: "れんしゅう", romaji: "renshuu", meaning: "practice", type: "Noun/Verb" },
      { word: "経験", furigana: "けいけん", romaji: "keiken", meaning: "experience", type: "Noun" },

      // Advanced Time
      { word: "今日", furigana: "きょう", romaji: "kyou", meaning: "today", type: "Time" },
      { word: "明日", furigana: "あした", romaji: "ashita", meaning: "tomorrow", type: "Time" },
      { word: "昨日", furigana: "きのう", romaji: "kinou", meaning: "yesterday", type: "Time" },
      { word: "来週", furigana: "らいしゅう", romaji: "raishuu", meaning: "next week", type: "Time" },
      { word: "今週", furigana: "こんしゅう", romaji: "konshuu", meaning: "this week", type: "Time" },
      { word: "先去週", furigana: "せんしゅう", romaji: "senshuu", meaning: "last week", type: "Time" },
      { word: "来月", furigana: "らいげつ", romaji: "raigetsu", meaning: "next month", type: "Time" },
      { word: "今月", furigana: "こんげつ", romaji: "kongetsu", meaning: "this month", type: "Time" },
      { word: "来年", furigana: "らいねん", romaji: "rainen", meaning: "next year", type: "Time" },
      { word: "今年", furigana: "ことし", romaji: "kotoshi", meaning: "this year", type: "Time" },
      { word: "毎朝", furigana: "まいあさ", romaji: "maiasa", meaning: "every morning", type: "Time" },
      { word: "毎週", furigana: "まいしゅう", romaji: "maishuu", meaning: "every week", type: "Time" },
      { word: "毎日", furigana: "まいにち", romaji: "mainichi", meaning: "every day", type: "Time" },

      // House & Daily Life
      { word: "部屋", furigana: "へや", romaji: "heya", meaning: "room", type: "Noun" },
      { word: "台所", furigana: "だいどころ", romaji: "daidokoro", meaning: "kitchen", type: "Noun" },
      { word: "風呂", furigana: "ふろ", romaji: "furo", meaning: "bath", type: "Noun" },
      { word: "洗濯", furigana: "せんたく", romaji: "sentaku", meaning: "laundry", type: "Noun" },
      { word: "掃除", furigana: "そうじ", romaji: "souji", meaning: "cleaning", type: "Noun" },
      { word: "料理", furigana: "りょうり", romaji: "ryouri", meaning: "cooking", type: "Noun" },
      { word: "食事", furigana: "しょくじ", romaji: "shokuji", meaning: "meal", type: "Noun" },
      { word: "病院", furigana: "びょういん", romaji: "byouin", meaning: "hospital", type: "Noun" },
      { word: "薬", furigana: "くすり", romaji: "kusuri", meaning: "medicine", type: "Noun" },
      { word: "準備", furigana: "じゅんび", romaji: "junbi", meaning: "preparation", type: "Noun" },
      { word: "用意", furigana: "ようい", romaji: "youi", meaning: "preparation", type: "Noun" },

      // Advanced Actions
      { word: "予約", furigana: "よyak", romaji: "yoyaku", meaning: "reservation", type: "Noun" },
      { word: "予約する", furigana: "よyakする", romaji: "yoyaku suru", meaning: "to make a reservation", type: "Verb" },
      { word: "説明する", furigana: "せつめいする", romaji: "setsumei suru", meaning: "to explain", type: "Verb" },
      { word: "注文", furigana: "ちゅうもん", romaji: "chuumon", meaning: "order", type: "Noun" },
      { word: "注文する", furigana: "ちゅうもんする", romaji: "chuumon suru", meaning: "to order", type: "Verb" },
      { word: "紹介", furigana: "しょうかい", romaji: "shoukai", meaning: "introduction", type: "Noun" },
      { word: "紹介する", furigana: "しょうかいする", romaji: "shoukai suru", meaning: "to introduce", type: "Verb" },
      { word: "調査", furigana: "ちょうさ", romaji: "chousa", meaning: "investigation", type: "Noun" },
      { word: "調査する", furigana: "ちょうさする", romaji: "chousa suru", meaning: "to investigate", type: "Verb" },
      { word: "準備する", furigana: "じゅんびする", romaji: "junbi suru", meaning: "to prepare", type: "Verb" },
      { word: "用意する", furigana: "よういする", romaji: "youi suru", meaning: "to prepare", type: "Verb" },
      { word: "運動", furigana: "うんどう", romaji: "undou", meaning: "exercise", type: "Noun" },
      { word: "運動する", furigana: "うんどうする", romaji: "undou suru", meaning: "to exercise", type: "Verb" },
      { word: "散歩", furigana: "さんぽ", romaji: "sanpo", meaning: "walk, stroll", type: "Noun" },
      { word: "散歩する", furigana: "さんぽする", romaji: "sanpo suru", meaning: "to take a walk", type: "Verb" },
      { word: "旅行", furigana: "りょこう", romaji: "ryokou", meaning: "travel", type: "Noun" },
      { word: "旅行する", furigana: "りょこうする", romaji: "ryokou suru", meaning: "to travel", type: "Verb" },
      { word: "過ごす", furigana: "すごす", romaji: "sugosu", meaning: "to spend (time)", type: "Verb" },
      { word: "経験する", furigana: "けいけんする", romaji: "keiken suru", meaning: "to experience", type: "Verb" },

      // Adjectives - More N4 level
      { word: "易しい", furigana: "やさしい", romaji: "yasashii", meaning: "easy", type: "Adjective" },
      { word: "難しい", furigana: "むずかしい", romaji: "muzukashii", meaning: "difficult", type: "Adjective" },
      { word: "広い", furigana: "ひろい", romaji: "hiroi", meaning: "wide, spacious", type: "Adjective" },
      { word: "狭い", furigana: "せまい", romaji: "semai", meaning: "narrow, cramped", type: "Adjective" },
      { word: "暗い", furigana: "くらい", romaji: "kurai", meaning: "dark", type: "Adjective" },
      { word: "明るい", furigana: "あかるい", romaji: "akarui", meaning: "bright", type: "Adjective" },
      { word: "近い", furigana: "ちかい", romaji: "chikai", meaning: "near", type: "Adjective" },
      { word: "遠い", furigana: "とおい", romaji: "tooi", meaning: "far", type: "Adjective" },
      { word: "早い", furigana: "はやい", romaji: "hayai", meaning: "fast, early", type: "Adjective" },
      { word: "遅い", furigana: "おそい", romaji: "osoi", meaning: "slow, late", type: "Adjective" },
      { word: "忙しい", furigana: "いそがしい", romaji: "isogashii", meaning: "busy", type: "Adjective" },
      { word: "楽しい", furigana: "たのしい", romaji: "tanoshii", meaning: "fun", type: "Adjective" },
      { word: "つまらない", furigana: "つまらない", romaji: "tsumaranai", meaning: "boring", type: "Adjective" },
      { word: "恥ずかしい", furigana: "はずかしい", romaji: "hazukashii", meaning: "embarrassed", type: "Adjective" },
      { word: "可惜", furigana: "あたらしい", romaji: "atarashii", meaning: "new", type: "Adjective" },
      { word: "祖父", furigana: "そふ", romaji: "sofu", meaning: "grandfather", type: "Noun" },
      { word: "祖母", furigana: "そば", romaji: "soba", meaning: "grandmother", type: "Noun" },
      { word: "調子", furigana: "ちょうし", romaji: "choushi", meaning: "condition", type: "Noun" },
      { word: "気分", furigana: "きぶん", romaji: "kibun", meaning: "feeling, mood", type: "Noun" },
      { word: "熱", furigana: "ねつ", romaji: "netsu", meaning: "fever", type: "Noun" },
      { word: "感情", furigana: "かんじょう", romaji: "kanjou", meaning: "emotion", type: "Noun" },

      // More Verbs
      { word: "調べる", furigana: "しらべる", romaji: "shiraberu", meaning: "to investigate", type: "Verb" },
      { word: "変える", furigana: "かえる", romaji: "kaeru", meaning: "to change", type: "Verb" },
      { word: "続ける", furigana: "つずける", romaji: "tsuzukeru", meaning: "to continue", type: "Verb" },
      { word: "止まる", furigana: "とまる", romaji: "tomaru", meaning: "to stop", type: "Verb" },
      { word: "守る", furigana: "まもる", romaji: "mamoru", meaning: "to protect", type: "Verb" },
      { word: "守る", furigana: "まもる", romaji: "mamoru", meaning: "to observe (rules)", type: "Verb" },
      { word: "進む", furigana: "すすむ", romaji: "susumu", meaning: "to proceed", type: "Verb" },
      { word: "連絡", furigana: "れんらく", romaji: "renraku", meaning: "contact", type: "Noun" },
      { word: "連絡する", furigana: "れんらくする", romaji: "renraku suru", meaning: "to contact", type: "Verb" },
      { word: "約束", furigana: "やくそく", romaji: "yakusoku", meaning: "promise", type: "Noun" },
      { word: "約束する", furigana: "やくそくする", romaji: "yakusoku suru", meaning: "to promise", type: "Verb" },
    ]
  },

  n3: {
    title: "JLPT N3 Vocabulary",
    description: "Intermediate vocabulary. Approximately 3,000 words for various situations.",
    vocabulary: [
      // Abstract Concepts
      { word: "意味", furigana: "いみ", romaji: "imi", meaning: "meaning", type: "Noun" },
      { word: "結果", furigana: "けっか", romaji: "kekka", meaning: "result", type: "Noun" },
      { word: "理由", furigana: "りゆう", romaji: "riyuu", meaning: "reason", type: "Noun" },
      { word: "関係", furigana: "かんけい", romaji: "kankei", meaning: "relationship", type: "Noun" },
      { word: "影響", furigana: "えいきょう", romaji: "eikyou", meaning: "influence", type: "Noun" },
      { word: "方法", furigana: "ほうほう", romaji: "houhou", meaning: "method", type: "Noun" },
      { word: "目的", furigana: "もくてき", romaji: "mokuteki", meaning: "purpose", type: "Noun" },
      { word: "理由", furigana: "りゆう", romaji: "riyuu", meaning: "reason, cause", type: "Noun" },
      { word: "説明", furigana: "せつめい", romaji: "setsumei", meaning: "explanation", type: "Noun" },
      { word: "理解", furigana: "りかい", romaji: "rikai", meaning: "understanding", type: "Noun" },
      { word: "経験", furigana: "けいけん", romaji: "keiken", meaning: "experience", type: "Noun" },
      { word: "記憶", furigana: "きおく", romaji: "kioku", meaning: "memory", type: "Noun" },
      { word: "知識", furigana: "ちしき", romaji: "chishiki", meaning: "knowledge", type: "Noun" },

      // Society & Culture
      { word: "社会", furigana: "しゃかい", romaji: "shakai", meaning: "society", type: "Noun" },
      { word: "文化", furigana: "ぶんか", romaji: "bunka", meaning: "culture", type: "Noun" },
      { word: "政治", furigana: "せいじ", romaji: "seiji", meaning: "politics", type: "Noun" },
      { word: "経済", furigana: "けいざい", romaji: "keizai", meaning: "economy", type: "Noun" },
      { word: "歴史", furigana: "れきし", romaji: "rekishi", meaning: "history", type: "Noun" },
      { word: "科学", furigana: "かがく", romaji: "kagaku", meaning: "science", type: "Noun" },
      { word: "技術", furigana: "ぎじゅつ", romaji: "gijutsu", meaning: "technology", type: "Noun" },
      { word: "教育", furigana: "きょういく", romaji: "kyouiku", meaning: "education", type: "Noun" },
      { word: "宗教", furigana: "しゅうきょう", romaji: "shuukyou", meaning: "religion", type: "Noun" },
      { word: "世界", furigana: "せかい", romaji: "sekai", meaning: "world", type: "Noun" },
      { word: "国民", furigana: "こくみん", romaji: "kokumin", meaning: "nation, people", type: "Noun" },
      { word: "国際", furigana: "こくさい", romaji: "kokusai", meaning: "international", type: "Noun" },

      // Mind & Psychology
      { word: "心理", furigana: "しんり", romaji: "shinri", meaning: "psychology", type: "Noun" },
      { word: "感情", furigana: "かんじょう", romaji: "kanjou", meaning: "emotion", type: "Noun" },
      { word: "意識", furigana: "いしき", romaji: "ishiki", meaning: "consciousness", type: "Noun" },
      { word: "考え", furigana: "かんがえ", romaji: "kangae", meaning: "thought", type: "Noun" },
      { word: "意見", furigana: "いけん", romaji: "iken", meaning: "opinion", type: "Noun" },
      { word: "興味", furigana: "きょうみ", romaji: "kyoumi", meaning: "interest", type: "Noun" },
      { word: "安心", furigana: "あんしん", romaji: "anshin", meaning: "peace of mind", type: "Noun" },
      { word: "希望", furigana: "きぼう", romaji: "kibou", meaning: "hope", type: "Noun" },
      { word: "残念", furigana: "ざんねん", romaji: "zannen", meaning: "regret", type: "Noun" },
      { word: "不平", furigana: "ふへい", romaji: "fuhei", meaning: "complaint", type: "Noun" },
      { word: "不平を言う", furigana: "ふへいをいう", romaji: "fuhei o iu", meaning: "to complain", type: "Verb" },
      { word: "感じ", furigana: "かんじ", romaji: "kanji", meaning: "feeling", type: "Noun" },

      // Advanced Actions
      { word: "研究", furigana: "けんきゅう", romaji: "kenkyuu", meaning: "research", type: "Noun" },
      { word: "研究する", furigana: "けんきゅうする", romaji: "kenkyuu suru", meaning: "to research", type: "Verb" },
      { word: "開発", furigana: "かいはつ", romaji: "kaihatsu", meaning: "development", type: "Noun" },
      { word: "開発する", furigana: "かいはつする", romaji: "kaihatsu suru", meaning: "to develop", type: "Verb" },
      { word: "準備", furigana: "じゅんび", romaji: "junbi", meaning: "preparation", type: "Noun" },
      { word: "準備する", furigana: "じゅんびする", romaji: "junbi suru", meaning: "to prepare", type: "Verb" },
      { word: "計画", furigana: "けいかく", romaji: "keikaku", meaning: "plan", type: "Noun" },
      { word: "計画する", furigana: "けいかくする", romaji: "keikaku suru", meaning: "to plan", type: "Verb" },
      { word: "提案", furigana: "ていあん", romaji: "teian", meaning: "proposal", type: "Noun" },
      { word: "提案する", furigana: "ていあんする", romaji: "teian suru", meaning: "to propose", type: "Verb" },
      { word: "実行", furigana: "じっこう", romaji: "jikkou", meaning: "execution", type: "Noun" },
      { word: "実行する", furigana: "じっこうする", romaji: "jikkou suru", meaning: "to execute", type: "Verb" },
      { word: "実現", furigana: "じつげん", romaji: "jitsugen", meaning: "realization", type: "Noun" },
      { word: "実現する", furigana: "じつげんする", romaji: "jitsugen suru", meaning: "to realize", type: "Verb" },
      { word: "確認", furigana: "かくにん", romaji: "kakunin", meaning: "confirmation", type: "Noun" },
      { word: "確認する", furigana: "かくにんする", romaji: "kakunin suru", meaning: "to confirm", type: "Verb" },
      { word: "比較", furigana: "ひかく", romaji: "hikaku", meaning: "comparison", type: "Noun" },
      { word: "比較する", furigana: "ひかくする", romaji: "hikaku suru", meaning: "to compare", type: "Verb" },
      { word: "評価", furigana: "ひょうか", romaji: "hyouka", meaning: "evaluation", type: "Noun" },
      { word: "評価する", furigana: "ひょうかする", romaji: "hyouka suru", meaning: "to evaluate", type: "Verb" },
      { word: "説明", furigana: "せつめい", romaji: "setsumei", meaning: "explanation", type: "Noun" },
      { word: "説明", furigana: "せつめいする", romaji: "setsumei suru", meaning: "to explain", type: "Verb" },
      { word: "議論", furigana: "ぎろん", romaji: "giron", meaning: "argument, discussion", type: "Noun" },
      { word: "議論する", furigana: "ぎろんする", romaji: "giron suru", meaning: "to argue, discuss", type: "Verb" },

      // Environment & Nature
      { word: "自然", furigana: "しぜん", romaji: "shizen", meaning: "nature", type: "Noun" },
      { word: "環境", furigana: "かんきょう", romaji: "kankyou", meaning: "environment", type: "Noun" },
      { word: "污染", furigana: "おせん", romaji: "osen", meaning: "pollution", type: "Noun" },
      { word: "資源", furigana: "しげん", romaji: "shigen", meaning: "resources", type: "Noun" },
      { word: "宇宙", furigana: "うちゅう", romaji: "uchuu", meaning: "universe", type: "Noun" },
      { word: "現象", furigana: "げんしょう", romaji: "genshou", meaning: "phenomenon", type: "Noun" },

      // More Adjectives
      { word: "典型的", furigana: "てんけいてき", romaji: "tenkeiteki", meaning: "typical", type: "Adjective" },
      { word: "重大的", furigana: "じゅうだいてき", romaji: "juudai teki", meaning: "serious, significant", type: "Adjective" },
      { word: "基本的", furigana: "きほんてき", romaji: "kihonteki", meaning: "basic", type: "Adjective" },
      { word: "特殊的", furigana: "とくしゅてき", romaji: "tokushuteki", meaning: "special", type: "Adjective" },
      { word: "同然", furigana: "どうぜん", romaji: "douzen", meaning: "only natural", type: "Adjective" },
      { word: "重要", furigana: "じゅうよう", romaji: "juuyou", meaning: "important", type: "Adjective" },
      { word: "必需的", furigana: "ひつようてき", romaji: "hitsuyouteki", meaning: "necessary", type: "Adjective" },
      { word: "十分な", furigana: "じゅうぶんな", romaji: "juubun na", meaning: "sufficient", type: "Adjective" },
      { word: "可能な", furigana: "かのうな", romaji: "kanou na", meaning: "possible", type: "Adjective" },
      { word: "不思議な", furigana: "ふしぎな", romaji: "fushigi na", meaning: "strange, mysterious", type: "Adjective" },

      // More Verbs
      { word: "理解する", furigana: "りかいする", romaji: "rikai suru", meaning: "to understand", type: "Verb" },
      { word: "感じる", furigana: "かんじる", romaji: "kanjiru", meaning: "to feel", type: "Verb" },
      { word: "信じる", furigana: "しんじる", romaji: "shinjiru", meaning: "to believe", type: "Verb" },
      { word: "疑う", furigana: "うたがう", romaji: "utagau", meaning: "to doubt", type: "Verb" },
      { word: "進める", furigana: "すすめる", romaji: "susumeru", meaning: "to advance, promote", type: "Verb" },
      { word: "引き返す", furigana: "ひきかえす", romaji: "hikikaesu", meaning: "to return, go back", type: "Verb" },
      { word: "応じる", furigana: "おうじる", romaji: "oujiru", meaning: "to respond", type: "Verb" },
      { word: "直面する", furigana: "ちょくめんする", romaji: "chokumen suru", meaning: "to face (a problem)", type: "Verb" },
      { word: "接触する", furigana: "せっしょくする", romaji: "sesshoku suru", meaning: "to contact", type: "Verb" },
      { word: "述べる", furigana: "のべる", romaji: "noberu", meaning: "to state", type: "Verb" },
      { word: "努める", furigana: "つとめる", romaji: "tsutomeru", meaning: "to endeavor", type: "Verb" },
    ]
  },

  n2: {
    title: "JLPT N2 Vocabulary",
    description: "Upper intermediate vocabulary. Approximately 6,000 words for complex situations.",
    vocabulary: [
      // Abstract Concepts
      { word: "存在", furigana: "そんざい", romaji: "sonzai", meaning: "existence", type: "Noun" },
      { word: "本質", furigana: "ほんしつ", romaji: "honshitsu", meaning: "essence", type: "Noun" },
      { word: "抽象", furigana: "ちゅうしょう", romaji: "chuushou", meaning: "abstract", type: "Noun" },
      { word: "概念", furigana: "がいねん", romaji: "gainen", meaning: "concept", type: "Noun" },
      { word: "認識", furigana: "にんしき", romaji: "ninshiki", meaning: "recognition", type: "Noun" },
      { word: "定義", furigana: "ていぎ", romaji: "teigi", meaning: "definition", type: "Noun" },
      { word: "原理", furigana: "げんり", romaji: "genri", meaning: "principle", type: "Noun" },
      { word: "法則", furigana: "ほうそく", romaji: "housoku", meaning: "law, rule", type: "Noun" },
      { word: "論理", furigana: "ろんり", romaji: "ronri", meaning: "logic", type: "Noun" },
      { word: "真実", furigana: "しんじつ", romaji: "shinjitsu", meaning: "truth", type: "Noun" },
      { word: "状態", furigana: "じょうたい", romaji: "joutai", meaning: "state, condition", type: "Noun" },
      { word: "現実", furigana: "げんじつ", romaji: "genjitsu", meaning: "reality", type: "Noun" },
      { word: "事実", furigana: "じじつ", romaji: "jijitsu", meaning: "fact", type: "Noun" },
      { word: "形", furigana: "かたち", romaji: "katachi", meaning: "shape, form", type: "Noun" },
      { word: "構造", furigana: "こうぞう", romaji: "kouzou", meaning: "structure", type: "Noun" },
      { word: "体系", furigana: "たいけい", romaji: "taikei", meaning: "system", type: "Noun" },
      { word: "総合", furigana: "そうごう", romaji: "sougou", meaning: "synthesis", type: "Noun" },
      { word: "分析", furigana: "ぶんせき", romaji: "bunseki", meaning: "analysis", type: "Noun" },
      { word: "分析する", furigana: "ぶんせきする", romaji: "bunseki suru", meaning: "to analyze", type: "Verb" },

      // Governance & Policy
      { word: "行政", furigana: "ぎょうせい", romaji: "gyousei", meaning: "administration", type: "Noun" },
      { word: "法律", furigana: "ほうりつ", romaji: "houritsu", meaning: "law", type: "Noun" },
      { word: "政策", furigana: "せいさく", romaji: "seisaku", meaning: "policy", type: "Noun" },
      { word: "政府", furigana: "せいふ", romaji: "seifu", meaning: "government", type: "Noun" },
      { word: "機関", furigana: "きかん", romaji: "kikan", meaning: "organization, agency", type: "Noun" },
      { word: "制度", furigana: "せいど", romaji: "seido", meaning: "system, institution", type: "Noun" },
      { word: "組織", furigana: "そしき", romaji: "soshiki", meaning: "organization", type: "Noun" },
      { word: "団体", furigana: "だんたい", romaji: "dantai", meaning: "group, organization", type: "Noun" },
      { word: "主義", furigana: "しゅぎ", romaji: "shugi", meaning: "principle, doctrine", type: "Noun" },
      { word: "思想", furigana: "しそう", romaji: "shisou", meaning: "thought, idea", type: "Noun" },
      { word: "外交", furigana: "がいこう", romaji: "gaikou", meaning: "diplomacy", type: "Noun" },
      { word: "権利", furigana: "けんり", romaji: "kenri", meaning: "rights", type: "Noun" },
      { word: "義務", furigana: "ぎむ", romaji: "gimu", meaning: "duty, obligation", type: "Noun" },
      { word: "平等", furigana: "びょうどう", romaji: "byoudou", meaning: "equality", type: "Noun" },

      // Science & Technology
      { word: "工学", furigana: "こうがく", romaji: "kougaku", meaning: "engineering", type: "Noun" },
      { word: "情報", furigana: "じょうほう", romaji: "jouhou", meaning: "information", type: "Noun" },
      { word: "通信", furigana: "つうしん", romaji: "tsuushin", meaning: "communication", type: "Noun" },
      { word: "電子", furigana: "でんし", romaji: "denshi", meaning: "electronic", type: "Noun" },
      { word: "機械", furigana: "きかい", romaji: "kikai", meaning: "machine", type: "Noun" },
      { word: "設備", furigana: "せつび", romaji: "setsubi", meaning: "equipment", type: "Noun" },
      { word: "実験", furigana: "じっけん", romaji: "jikken", meaning: "experiment", type: "Noun" },
      { word: "理論", furigana: "り론", romaji: "riron", meaning: "theory", type: "Noun" },
      { word: "傾向", furigana: "けいこう", romaji: "keikou", meaning: "tendency", type: "Noun" },
      { word: "可能性", furigana: "かのうせい", romaji: "kanousei", meaning: "possibility", type: "Noun" },
      { word: "現実的", furigana: "げんじつてき", romaji: "genjitsuteki", meaning: "realistic", type: "Adjective" },

      // Business & Management
      { word: "企業", furigana: "きぎょう", romaji: "kigyou", meaning: "enterprise", type: "Noun" },
      { word: "経営", furigana: "けいえい", romaji: "keiei", meaning: "management", type: "Noun" },
      { word: "競争", furigana: "きょうそう", romaji: "kyousou", meaning: "competition", type: "Noun" },
      { word: "市場", furigana: "しじょう", romaji: "shijou", meaning: "market", type: "Noun" },
      { word: "取引", furigana: "とりひき", romaji: "torihiki", meaning: "transaction", type: "Noun" },
      { word: "契約", furigana: "けいやく", romaji: "keiyaku", meaning: "contract", type: "Noun" },
      { word: "広告", furigana: "こうこく", romaji: "koukoku", meaning: "advertisement", type: "Noun" },
      { word: "営業", furigana: "えいぎょう", romaji: "eigyou", meaning: "sales, business", type: "Noun" },
      { word: "投資", furigana: "とうし", romaji: "toushi", meaning: "investment", type: "Noun" },
      { word: "方針", furigana: "ほうしん", romaji: "houshin", meaning: "policy, plan", type: "Noun" },
      { word: "戦略", furigana: "せんりゃく", romaji: "senryaku", meaning: "strategy", type: "Noun" },
      { word: "部署", furigana: "ぶしょ", romaji: "busho", meaning: "department", type: "Noun" },
      { word: "成功", furigana: "せいこう", romaji: "seikou", meaning: "success", type: "Noun" },
      { word: "失敗", furigana: "しっぱい", romaji: "shippai", meaning: "failure", type: "Noun" },
      { word: "規則", furigana: "きそく", romaji: "kisoku", meaning: "rule, regulation", type: "Noun" },
      { word: "提供", furigana: "ていきょう", romaji: "teikyou", meaning: "offer, provide", type: "Noun" },

      // Psychology & Emotions
      { word: "感覚", furigana: "かんかく", romaji: "kankaku", meaning: "sensation", type: "Noun" },
      { word: "思考", furigana: "しこう", romaji: "shikou", meaning: "thought", type: "Noun" },
      { word: "精神", furigana: "せいしん", romaji: "seishin", meaning: "mind, spirit", type: "Noun" },
      { word: "意志", furigana: "いし", romaji: "ishi", meaning: "will, intention", type: "Noun" },
      { word: "理性", furigana: "りせい", romaji: "risei", meaning: "reason, rationality", type: "Noun" },
      { word: "本能", furigana: "ほんのう", romaji: "honnou", meaning: "instinct", type: "Noun" },
      { word: "性格", furigana: "せいかく", romaji: "seikaku", meaning: "personality", type: "Noun" },
      { word: "人間", furigana: "にんげん", romaji: "ningen", meaning: "human being", type: "Noun" },
      { word: "互い", furigana: "たがい", romaji: "tagai", meaning: "each other", type: "Noun" },
      { word: "心情", furigana: "しんじょう", romaji: "shinjou", meaning: "emotional state", type: "Noun" },
      { word: "信念", furigana: "しんねん", romaji: "shinnen", meaning: "belief", type: "Noun" },
      { word: "傾向", furigana: "けいこう", romaji: "keikou", meaning: "tendency", type: "Noun" },

      // More Advanced Verbs
      { word: "提唱する", furigana: "ていしょうする", romaji: "teishou suru", meaning: "to propose", type: "Verb" },
      { word: "排斥する", furigana: "はいせきする", romaji: "haiseki suru", meaning: "to reject", type: "Verb" },
      { word: "活用する", furigana: "かつようする", romaji: "katsuyou suru", meaning: "to utilize", type: "Verb" },
      { word: "調和", furigana: "ちょうわ", romaji: "chouwa", meaning: "harmony", type: "Noun" },
      { word: "調和する", furigana: "ちょうわする", romaji: "chouwa suru", meaning: "to harmonize", type: "Verb" },
      { word: "統合する", furigana: "とうごうする", romaji: "tougou suru", meaning: "to integrate", type: "Verb" },
      { word: "促進する", furigana: "そくしんする", romaji: "sokushin suru", meaning: "to promote", type: "Verb" },
      { word: "抑制する", furigana: "よくせいする", romaji: " yokusei suru", meaning: "to suppress", type: "Verb" },
      { word: "確保する", furigana: "かくほする", romaji: "kakuho suru", meaning: "to secure", type: "Verb" },
      { word: "達成する", furigana: "たっせいする", romaji: "tassei suru", meaning: "to achieve", type: "Verb" },
      { word: "証明する", furigana: "しょうめいする", romaji: "shoumei suru", meaning: "to prove", type: "Verb" },
      { word: "象徴する", furigana: "しょうちょうする", romaji: "shouchou suru", meaning: "to symbolize", type: "Verb" },
      { word: "類推する", furigana: "るいすいする", romaji: "ruisui suru", meaning: "to analogize", type: "Verb" },
      { word: "概括する", furigana: "がいかつする", romaji: "gaikatsu suru", meaning: "to generalize", type: "Verb" },
    ]
  },

  n1: {
    title: "JLPT N1 Vocabulary",
    description: "Advanced vocabulary. Approximately 10,000 words for mastery.",
    vocabulary: [
      // Highest Level Abstract
      { word: "存在", furigana: "そんざい", romaji: "sonzai", meaning: "existence, being", type: "Noun" },
      { word: "本質", furigana: "ほんしつ", romaji: "honshitsu", meaning: "essence, substance", type: "Noun" },
      { word: "実体", furigana: "じったい", romaji: "jittai", meaning: "substance, entity", type: "Noun" },
      { word: "実在", furigana: "じつざい", romaji: "jitsuzai", meaning: "actuality, existence", type: "Noun" },
      { word: "客体", furigana: "きゃくたい", romaji: "kyakutai", meaning: "object", type: "Noun" },
      { word: "主体", furigana: "しゅたい", romaji: "shutai", meaning: "subject, main part", type: "Noun" },
      { word: "主体性", furigana: "しゅたいせい", romaji: "shutaisei", meaning: "subjectivity", type: "Noun" },
      { word: "客観", furigana: "きゃっかん", romaji: "kyakkan", meaning: "objectivity", type: "Noun" },
      { word: "主観", furigana: "しゅかん", romaji: "shukan", meaning: "subjectivity", type: "Noun" },
      { word: "形而上", furigana: "けいじじょう", romaji: "keijijou", meaning: "metaphysical", type: "Noun" },
      { word: "形而下", furigana: "けいじか", romaji: "keijika", meaning: "physical", type: "Noun" },
      { word: "表象", furigana: "ひょうしょう", romaji: "hyoushou", meaning: "representation", type: "Noun" },
      { word: "象徵", furigana: "しょうちょう", romaji: "shouchou", meaning: "symbol", type: "Noun" },
      { word: "具象", furigana: "ぐしょう", romaji: "gushou", meaning: "concrete", type: "Noun" },
      { word: "概括", furigana: "がいかつ", romaji: "gaikatsu", meaning: "generalization", type: "Noun" },
      { word: "帰納", furigana: "きのう", romaji: "kinou", meaning: "induction", type: "Noun" },
      { word: "演繹", furigana: "えんえき", romaji: "en'eki", meaning: "deduction", type: "Noun" },
      { word: "定立", furigana: "ていりつ", romaji: "teiritsu", meaning: "thesis", type: "Noun" },
      { word: "反定立", furigana: "はんていりつ", romaji: "hanteiritsu", meaning: "antithesis", type: "Noun" },
      { word: "合定立", furigana: "ごうていりつ", romaji: "gouteiritsu", meaning: "synthesis", type: "Noun" },

      // Advanced Philosophy
      { word: "弁証法", furigana: "べんしょうほう", romaji: "benshouhou", meaning: "dialectics", type: "Noun" },
      { word: "唯物論", furigana: "ゆいぶつ론", romaji: "yuibutsuron", meaning: "materialism", type: "Noun" },
      { word: "観念論", furigana: "かんねん론", romaji: "kannenenron", meaning: "idealism", type: "Noun" },
      { word: "実存", furigana: "じつぞん", romaji: "jitsuzon", meaning: "existence", type: "Noun" },
      { word: "実存主義", furigana: "じつぞんしゅぎ", romaji: "jitsuzon shugi", meaning: "existentialism", type: "Noun" },
      { word: "合理主義", furigana: "ごうりしゅぎ", romaji: "gourishugi", meaning: "rationalism", type: "Noun" },
      { word: "経験主義", furigana: "けいけんしゅぎ", romaji: "keikenshugi", meaning: "empiricism", type: "Noun" },
      { word: "主知主義", furigana: "しゅちしゅぎ", romaji: "shuchishugi", meaning: "intellectualism", type: "Noun" },
      { word: "形式主義", furigana: "けいしきしゅぎ", romaji: "keishikishugi", meaning: "formalism", type: "Noun" },
      { word: "官僚主義", furigana: "かんりょうしゅぎ", romaji: "kanryoushugi", meaning: "bureaucratism", type: "Noun" },

      // Advanced Social/Political
      { word: "権力", furigana: "けんりょく", romaji: "kenryoku", meaning: "power", type: "Noun" },
      { word: "権威", furigana: "けんい", romaji: "ken'i", meaning: "authority", type: "Noun" },
      { word: "権原", furigana: "けんげん", romaji: "kengen", meaning: "basis of authority", type: "Noun" },
      { word: "支配", furigana: "しはく", romaji: "shihai", meaning: "control, rule", type: "Noun" },
      { word: "支配する", furigana: "しはくする", romaji: "shihai suru", meaning: "to rule, control", type: "Verb" },
      { word: "搾取", furigana: "さくしゅ", romaji: "sakushu", meaning: "exploitation", type: "Noun" },
      { word: "搾取する", furigana: "さくしゅする", romaji: "sakushu suru", meaning: "to exploit", type: "Verb" },
      { word: "収奪", furigana: "しゅうだつ", romaji: "shuudatsu", meaning: "plunder", type: "Noun" },
      { word: "収奪する", furigana: "しゅうだつする", romaji: "shuudatsu suru", meaning: "to plunder", type: "Verb" },
      { word: "封建制", furigana: "ほうけんせい", romaji: "houkensei", meaning: "feudalism", type: "Noun" },
      { word: "資本主義", furigana: "しほんしゅぎ", romaji: "shihonshugi", meaning: "capitalism", type: "Noun" },
      { word: "社会主義", furigana: "しゃかいしゅぎ", romaji: "shakaishugi", meaning: "socialism", type: "Noun" },
      { word: "民主主義", furigana: "みんしゅしゅぎ", romaji: "minshushugi", meaning: "democracy", type: "Noun" },
      { word: "全体主義", furigana: "ぜんたいしゅぎ", romaji: "zentaishugi", meaning: "totalitarianism", type: "Noun" },
      { word: "排外主義", furigana: "はいがいしゅぎ", romaji: "haigaishugi", meaning: "xenophobia", type: "Noun" },
      { word: "宽容", furigana: "かんよう", romaji: "kanyou", meaning: "tolerance", type: "Noun" },
      { word: "耐久", furigana: "たいきゅう", romaji: "taikyuu", meaning: "durability", type: "Noun" },
      { word: "隠廃", furigana: "いんはい", romaji: "inhai", meaning: "concealment and abolition", type: "Noun" },
      { word: "変革", furigana: "へんかく", romaji: "henkaku", meaning: "transformation", type: "Noun" },

      // Advanced Science
      { word: "細胞", furigana: "さいぼう", romaji: "saibou", meaning: "cell", type: "Noun" },
      { word: "遺伝子", furigana: "いでんし", romaji: "idenshi", meaning: "gene", type: "Noun" },
      { word: "進化", furigana: "しんか", romaji: "shinka", meaning: "evolution", type: "Noun" },
      { word: "退化", furigana: "たいか", romaji: "taika", meaning: "degeneration", type: "Noun" },
      { word: "突然変異", furigana: "とつぜんへんい", romaji: "totsuzen hen'i", meaning: "mutation", type: "Noun" },
      { word: "適者生存", furigana: "てきしゃせいぞん", romaji: "tekisha seizon", meaning: "survival of the fittest", type: "Noun" },
      { word: "生態系", furigana: "せいたいけい", romaji: "seitaikei", meaning: "ecosystem", type: "Noun" },
      { word: "環境問題", furigana: "かんきょうもんだい", romaji: "kankyou mondai", meaning: "environmental problem", type: "Noun" },
      { word: "資源の枯渇", furigana: "しげんのか кося", romaji: "shigen no kokatsu", meaning: "resource depletion", type: "Noun" },
      { word: "酸性雨", furigana: "さんせいう", romaji: "sanseiu", meaning: "acid rain", type: "Noun" },
      { word: "溫室効果", furigana: "おんしつこうか", romaji: "onshitsu kouka", meaning: "greenhouse effect", type: "Noun" },
      { word: "オゾン層", furigana: "おぞんそう", romaji: "ozon sou", meaning: "ozone layer", type: "Noun" },
      { word: "放射能", furigana: "ほうしゃのう", romaji: "houshanou", meaning: "radioactivity", type: "Noun" },
      { word: "核分裂", furigana: "かくぶんれつ", romaji: "kakubunretsu", meaning: "nuclear fission", type: "Noun" },
      { word: "核融合", furigana: "かくゆうごう", romaji: "kakuyuugou", meaning: "nuclear fusion", type: "Noun" },

      // Advanced Verbs
      { word: "定義する", furigana: "ていぎする", romaji: "teigi suru", meaning: "to define", type: "Verb" },
      { word: "分類する", furigana: "ぶんるいする", romaji: "bunrui suru", meaning: "to classify", type: "Verb" },
      { word: "限定する", furigana: "げんていする", romaji: "gentei suru", meaning: "to limit", type: "Verb" },
      { word: "特定する", furigana: "とくていする", romaji: "tokutei suru", meaning: "to specify", type: "Verb" },
      { word: "象徴する", furigana: "しょうちょうする", romaji: "shouchou suru", meaning: "to symbolize", type: "Verb" },
      { word: "具体化する", furigana: "ぐたいかする", romaji: "gutrika suru", meaning: "to make concrete", type: "Verb" },
      { word: "抽象化する", furigana: "ちゅうしょうかする", romaji: "chuushouka suru", meaning: "to abstract", type: "Verb" },
      { word: "理論化する", furigana: "りろんかする", romaji: "rironka suru", meaning: "to theorize", type: "Verb" },
      { word: "体系化する", furigana: "たいけいかする", romaji: "taikeika suru", meaning: "to systematize", type: "Verb" },
      { word: "構造化する", furigana: "こうぞうかする", romaji: "kouzouka suru", meaning: "to structure", type: "Verb" },
      { word: "認識する", furigana: "にんしきする", romaji: "ninshiki suru", meaning: "to recognize", type: "Verb" },
      { word: "理解する", furigana: "りかいする", romaji: "rikai suru", meaning: "to understand", type: "Verb" },
      { word: "把握する", furigana: "はあくする", romaji: "haaku suru", meaning: "to grasp", type: "Verb" },
      { word: "洞察する", furigana: "どうさする", romaji: "dousa suru", meaning: "to insight", type: "Verb" },
      { word: "見通す", furigana: "みとおす", romaji: "mitoosu", meaning: "to foresee", type: "Verb" },
      { word: "展望する", furigana: "てんぼうする", romaji: "tenbou suru", meaning: "to look ahead", type: "Verb" },
      { word: "推測する", furigana: "すいそくする", romaji: "suisoku suru", meaning: "to speculate", type: "Verb" },
      { word: "推理する", furigana: "すいりする", romaji: "suiri suru", meaning: "to infer", type: "Verb" },
      { word: "結論づける", furigana: "けつろんづける", romaji: "ketsuron dukeru", meaning: "to conclude", type: "Verb" },
      { word: "断定する", furigana: "だんていする", romaji: "dantei suru", meaning: "to conclude, determine", type: "Verb" },
      { word: "解釈する", furigana: "かいしゃくする", romaji: "kaishaku suru", meaning: "to interpret", type: "Verb" },
      { word: "評価する", furigana: "ひょうかする", romaji: "hyouka suru", meaning: "to evaluate", type: "Verb" },
      { word: "判断する", furigana: "はんだんする", romaji: "handan suru", meaning: "to judge", type: "Verb" },
      { word: "決断する", furigana: "けつだんする", romaji: "ketsudan suru", meaning: "to decide", type: "Verb" },
      { word: "決意する", furigana: "けついする", romaji: "ketsui suru", meaning: "to resolve", type: "Verb" },
      { word: "決意表明", furigana: "けついひょうめい", romaji: "ketsui hyoumei", meaning: "declaration of intent", type: "Noun" },
    ]
  }
};
